# Generated by Django 4.1.5 on 2023-02-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0003_trip_occasion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_start_date',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
