# Generated by Django 4.1.5 on 2023-02-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0004_accessorie_clothing_comfort_electronic_health_shoe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electronic',
            old_name='electronics',
            new_name='Electronic',
        ),
    ]
