# Generated by Django 4.1.5 on 2023-02-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0005_rename_electronics_electronic_electronic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
