# Generated by Django 4.1.5 on 2023-02-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0006_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
