# Generated by Django 4.1.5 on 2023-02-17 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0007_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='description',
        ),
    ]
