# Generated by Django 4.1.5 on 2023-02-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0007_trip_num_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='num_days',
            new_name='length_of_trip',
        ),
    ]
