# Generated by Django 4.1.5 on 2023-02-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0008_remove_gender_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='gen',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=20),
        ),
    ]
