# Generated by Django 4.1.5 on 2023-02-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0009_gender_item_category_generated_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_range', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
