# Generated by Django 4.1.5 on 2023-02-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0010_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='temp_range',
            field=models.CharField(default='', max_length=150),
        ),
    ]
