# Generated by Django 4.1.5 on 2023-02-17 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('occasion', '0010_rename_description_shoe_shoes_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_destination', models.CharField(max_length=150)),
                ('trip_start_date', models.CharField(max_length=150)),
                ('trip_end_date', models.CharField(max_length=150)),
                ('trip_weather', models.CharField(max_length=150)),
                ('occasion', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('trip_gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.gender')),
                ('trip_item_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.item_category')),
                ('trip_occasion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.occasion')),
                ('trip_userID', models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
