# Generated by Django 4.1.5 on 2023-02-17 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0011_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorie',
            name='accessories_gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.gender'),
        ),
        migrations.AddField(
            model_name='accessorie',
            name='accessories_item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.item_category'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='clothing_gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.gender'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='clothing_item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.item_category'),
        ),
        migrations.AddField(
            model_name='comfort',
            name='comfort_gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.gender'),
        ),
        migrations.AddField(
            model_name='comfort',
            name='comfort_item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.item_category'),
        ),
        migrations.AddField(
            model_name='electronic',
            name='electronic_gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.gender'),
        ),
        migrations.AddField(
            model_name='electronic',
            name='electronic_item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.item_category'),
        ),
        migrations.AddField(
            model_name='essential',
            name='essentials_gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.gender'),
        ),
        migrations.AddField(
            model_name='essential',
            name='essentials_item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.item_category'),
        ),
        migrations.AddField(
            model_name='health',
            name='health_gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.gender'),
        ),
        migrations.AddField(
            model_name='health',
            name='health_item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.item_category'),
        ),
        migrations.AddField(
            model_name='occasion',
            name='occasion_gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.gender'),
        ),
        migrations.AddField(
            model_name='occasion',
            name='occasion_item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.item_category'),
        ),
        migrations.AddField(
            model_name='toiletrie',
            name='toiletries_gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.gender'),
        ),
        migrations.AddField(
            model_name='toiletrie',
            name='toiletries_item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.item_category'),
        ),
    ]
