# Generated by Django 4.1.5 on 2023-02-17 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0012_accessorie_accessories_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Shoes', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('shoes_gender', models.ForeignKey(default='Male', on_delete=django.db.models.deletion.CASCADE, to='occasion.gender')),
                ('shoes_item_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.item_category')),
            ],
        ),
        migrations.DeleteModel(
            name='Shoe',
        ),
    ]
