# Generated by Django 4.1.5 on 2023-02-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0012_shoe_shoes_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='comfort',
            name='clothing_temp',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='gender',
            name='gen',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=150, null=True),
        ),
    ]
