# Generated by Django 4.1.5 on 2023-02-17 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0013_shoes_delete_shoe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generated_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_qty_of_clothing', models.CharField(max_length=150)),
                ('gen_weather', models.CharField(max_length=150)),
                ('gen_accessories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.accessorie')),
                ('gen_clothing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.clothing')),
                ('gen_comfort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.comfort')),
                ('gen_electronic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.electronic')),
                ('gen_essentials', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.essential')),
                ('gen_gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.gender')),
                ('gen_health', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.health')),
                ('gen_item_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.item_category')),
                ('gen_occasion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.occasion')),
                ('gen_shoe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.shoes')),
                ('gen_toiletries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.toiletrie')),
                ('gen_tripID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.trip')),
            ],
        ),
    ]
