# Generated by Django 4.1.5 on 2023-02-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0013_comfort_clothing_temp_alter_gender_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='clothing_temp',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='gender',
            name='gen',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=150, null=True),
        ),
    ]
