# Generated by Django 4.1.5 on 2023-02-28 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0014_clothing_clothing_temp_alter_gender_gen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essential',
            name='essentials_gender',
        ),
    ]
