# Generated by Django 4.1.5 on 2023-02-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0015_remove_essential_essentials_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorie',
            name='accessories_temp',
            field=models.CharField(default='', max_length=150),
        ),
    ]
