# Generated by Django 4.1.5 on 2023-03-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0018_delete_weather_remove_electronic_electronic_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
