# Generated by Django 4.1.5 on 2023-03-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0020_trip_activities_alter_accessorie_accessories_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='shoes_temperature',
            field=models.CharField(default='Warm', max_length=10),
        ),
    ]
