# Generated by Django 4.1.5 on 2023-03-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0022_shoe_shoes_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='shoes_activity',
        ),
        migrations.AddField(
            model_name='shoe',
            name='shoes_activity',
            field=models.ManyToManyField(blank=True, related_name='shoes', to='occasion.activities'),
        ),
    ]
