# Generated by Django 4.1.5 on 2023-03-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0023_remove_shoe_shoes_activity_shoe_shoes_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='shoes_activity',
        ),
        migrations.AddField(
            model_name='shoe',
            name='shoes_activity',
            field=models.CharField(default='', max_length=150),
        ),
    ]
