# Generated by Django 4.1.5 on 2023-03-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0024_remove_shoe_shoes_activity_shoe_shoes_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='shoes_activity',
        ),
        migrations.AddField(
            model_name='shoe',
            name='shoes_activities',
            field=models.ManyToManyField(to='occasion.activities'),
        ),
    ]
