# Generated by Django 4.1.5 on 2023-03-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0025_remove_shoe_shoes_activity_shoe_shoes_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential',
            name='essential_activities',
            field=models.ManyToManyField(to='occasion.activities'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
