# Generated by Django 4.1.5 on 2023-03-03 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0026_essential_essential_activities_alter_activities_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essential',
            name='essential_activities',
        ),
    ]
