# Generated by Django 4.1.5 on 2023-03-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0027_remove_essential_essential_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='shoes_activities',
        ),
        migrations.AddField(
            model_name='shoe',
            name='shoes_activities',
            field=models.CharField(default='', max_length=150),
        ),
    ]
