# Generated by Django 4.1.5 on 2023-03-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0029_shoe_shoes_occasion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='clothing_activity',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='clothing',
            name='clothing_occasion',
            field=models.CharField(default='Leisure', max_length=150),
        ),
    ]
