# Generated by Django 4.1.5 on 2023-03-04 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0030_clothing_clothing_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='clothing_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.activities'),
        ),
    ]
