# Generated by Django 4.1.5 on 2023-03-04 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0032_remove_generated_list_gen_occasion_delete_occasion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment', models.CharField(max_length=150)),
                ('clothing_temp', models.CharField(default='', max_length=150)),
                ('clothing_occasion', models.CharField(default='Leisure', max_length=150)),
                ('clothing_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.activities')),
            ],
        ),
    ]
