# Generated by Django 4.1.5 on 2023-03-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0033_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='clothing_item_category',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='description',
        ),
    ]
