# Generated by Django 4.1.5 on 2023-03-04 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0034_remove_clothing_clothing_item_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessorie',
            name='accessories_item_category',
        ),
        migrations.RemoveField(
            model_name='accessorie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='comfort',
            name='comfort_item_category',
        ),
        migrations.RemoveField(
            model_name='comfort',
            name='description',
        ),
        migrations.RemoveField(
            model_name='electronic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='electronic',
            name='electronic_item_category',
        ),
        migrations.RemoveField(
            model_name='essential',
            name='description',
        ),
        migrations.RemoveField(
            model_name='essential',
            name='essentials_item_category',
        ),
        migrations.RemoveField(
            model_name='generated_list',
            name='gen_description',
        ),
        migrations.RemoveField(
            model_name='generated_list',
            name='gen_item_category',
        ),
        migrations.RemoveField(
            model_name='health',
            name='description',
        ),
        migrations.RemoveField(
            model_name='health',
            name='health_item_category',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='shoes_item_category',
        ),
        migrations.RemoveField(
            model_name='toiletrie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='toiletrie',
            name='toiletries_item_category',
        ),
        migrations.DeleteModel(
            name='Item_Category',
        ),
    ]
