# Generated by Django 4.1.5 on 2023-03-04 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0035_remove_accessorie_accessories_item_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='clothing_temp',
        ),
    ]
