# Generated by Django 4.1.5 on 2023-03-04 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0036_remove_equipment_clothing_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comfort',
            name='clothing_temp',
        ),
        migrations.RemoveField(
            model_name='comfort',
            name='comfort_gender',
        ),
    ]
