# Generated by Django 4.1.5 on 2023-03-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0037_remove_comfort_clothing_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='clothing_activity',
        ),
        migrations.AddField(
            model_name='clothing',
            name='clothing_activity',
            field=models.ManyToManyField(to='occasion.activities'),
        ),
    ]
