# Generated by Django 4.1.5 on 2023-03-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0042_occasion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='clothing_occasion',
        ),
        migrations.AddField(
            model_name='clothing',
            name='clothing_occasion',
            field=models.ManyToManyField(to='occasion.occasion'),
        ),
    ]
