# Generated by Django 4.1.5 on 2023-03-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0045_remove_clothing_clothing_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='clothing_temp',
        ),
        migrations.AddField(
            model_name='clothing',
            name='clothing_temp',
            field=models.ManyToManyField(to='occasion.temprange'),
        ),
    ]
