# Generated by Django 4.1.5 on 2023-03-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0046_temprange_remove_clothing_clothing_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='temp_range',
            field=models.CharField(max_length=150),
        ),
    ]
