# Generated by Django 4.1.5 on 2023-03-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0047_alter_trip_temp_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='clothing_activity',
        ),
        migrations.AddField(
            model_name='clothing',
            name='clothing_activity',
            field=models.ManyToManyField(to='occasion.activities'),
        ),
    ]
