# Generated by Django 4.1.5 on 2023-03-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0049_remove_generated_list_gen_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generated_list',
            name='gen_clothing',
        ),
        migrations.AddField(
            model_name='generated_list',
            name='gen_clothing',
            field=models.ManyToManyField(to='occasion.clothing'),
        ),
    ]
