# Generated by Django 4.1.5 on 2023-03-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0055_generated_list_gen_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_activity',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_activity',
            field=models.ManyToManyField(to='occasion.activities'),
        ),
    ]
