# Generated by Django 4.1.5 on 2023-03-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0056_remove_equipment_equipment_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
