# Generated by Django 4.1.5 on 2023-03-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0057_alter_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generated_list',
            name='gen_trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gen_trip', to='occasion.trip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generated_list',
            name='gen_tripID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_tripID', to='occasion.trip'),
        ),
    ]
