# Generated by Django 4.1.5 on 2023-03-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0058_generated_list_gen_trip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generated_list',
            name='gen_trip',
        ),
        migrations.AlterField(
            model_name='generated_list',
            name='gen_tripID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occasion.trip'),
        ),
    ]
