# Generated by Django 4.1.5 on 2023-03-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0059_remove_generated_list_gen_trip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_occasion',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_occasion',
            field=models.ManyToManyField(to='occasion.occasion'),
        ),
    ]
